# Generated by Django 5.1.4 on 2024-12-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewlyHiredStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements_ok', models.BooleanField(default=False, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('area_of_assignment', models.CharField(max_length=100)),
                ('former_incumbent', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effectivity_of_contract', models.DateField()),
                ('end_of_contract', models.DateField()),
                ('emp_status', models.CharField(max_length=100, null=True)),
                ('nature', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
