# Generated by Django 4.2.16 on 2025-01-06 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEndorsementActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('lib_endorsed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsp.endorsementactivities')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsp.newlyhiredstaff')),
            ],
        ),
    ]
