# Generated by Django 5.1.4 on 2024-12-12 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlyhiredstaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newlyhiredstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
