# Generated by Django 4.2.16 on 2025-01-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rspempstatus',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='rsphiredreq',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='rsphiredstreamlinereq',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
