# Generated by Django 4.2.16 on 2025-01-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffneopactivities',
            name='is_email_notify',
        ),
        migrations.AddField(
            model_name='libcosguidelinesactivities',
            name='is_email_notify',
            field=models.BooleanField(default=0),
        ),
    ]
