# Generated by Django 4.2.18 on 2025-01-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredreqcompliance',
            name='is_required',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
