# Generated by Django 4.2.16 on 2024-12-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0002_libcosguidelinesactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCosGuidelinesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption_date', models.DateField(blank=True, null=True)),
                ('requirements_submission_date', models.DateField(blank=True, null=True)),
                ('ccef_submission_date', models.DateField(blank=True, null=True)),
                ('agency_orientation', models.DateField(blank=True, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cos_guidelines_info_activities', to='rsp.newlyhiredstaff')),
            ],
        ),
    ]
