# Generated by Django 4.2.16 on 2025-01-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0002_remove_staffneopactivities_is_email_notify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffneopinfo',
            name='date_end_x',
            field=models.DateField(blank=True, null=True),
        ),
    ]
