# Generated by Django 4.2.16 on 2025-01-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0002_staffendorsementactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiredreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_required', models.IntegerField()),
                ('status', models.IntegerField()),
                ('upload_by_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rsp_hiredreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HiredreqCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rsp_hiredreq_compliance',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='newlyhiredstaff',
            name='app_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newlyhiredstaff',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlyhiredstaff',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlyhiredstaff',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlyhiredstaffstreamline',
            name='app_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newlyhiredstaffstreamline',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlyhiredstaffstreamline',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlyhiredstaffstreamline',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
