# Generated by Django 4.2.18 on 2025-01-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0002_hiredreqcompliance_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlyhiredstaff',
            name='araf_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiredreqcompliance',
            name='is_required',
            field=models.BooleanField(default=0),
        ),
    ]
