# Generated by Django 4.2.16 on 2025-01-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0003_hiredreq_hiredreqcompliance_newlyhiredstaff_app_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingStatusNewlyhired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rsp.newlyhiredstaff')),
                ('onboarding_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rsp.onboardingstatus')),
            ],
        ),
        migrations.AlterField(
            model_name='newlyhiredstaff',
            name='onboarding_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rsp.onboardingstatus'),
        ),
    ]
