# Generated by Django 4.2.16 on 2025-01-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0003_staffneopinfo_date_end_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffneopinfo',
            name='date_end_x',
        ),
    ]
