# Generated by Django 4.2.16 on 2024-12-26 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0003_staffcosguidelinesinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCosGuidelinesActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('lib_neop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_cos_activities', to='rsp.libneopactivities')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cos_activities', to='rsp.newlyhiredstaff')),
            ],
        ),
    ]
