# Generated by Django 5.1.4 on 2024-12-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0004_alter_newlyhiredstaff_effectivity_of_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlyhiredstaff',
            name='end_of_contract',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
