# Generated by Django 4.2.16 on 2024-12-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0004_staffcosguidelinesactivities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcosguidelinesactivities',
            old_name='lib_neop_id',
            new_name='lib_cos_guidelines_id',
        ),
    ]
