# Generated by Django 5.1.4 on 2024-12-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0005_alter_newlyhiredstaff_end_of_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlyhiredstaff',
            name='area_of_assignment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newlyhiredstaff',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newlyhiredstaff',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newlyhiredstaff',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
