# Generated by Django 4.2.17 on 2024-12-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0006_alter_newlyhiredstaff_area_of_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlyhiredstaff',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
