# Generated by Django 4.2.16 on 2025-01-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0007_newlyhiredstaff_iris_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlyhiredstaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newlyhiredstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='newlyhiredstaffstreamline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newlyhiredstaffstreamline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
