# Generated by Django 4.2.16 on 2024-12-18 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0008_libneopactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNeopActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('lib_neop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_activities', to='rsp.libneopactivities')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neop_activities', to='rsp.newlyhiredstaff')),
            ],
            options={
                'unique_together': {('staff_id', 'lib_neop_id')},
            },
        ),
    ]
