# Generated by Django 4.2.16 on 2024-12-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0009_staffneopactivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffneopactivities',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staffneopactivities',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
