# Generated by Django 4.2.16 on 2024-12-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0010_staffneopactivities_date_staffneopactivities_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffneopactivities',
            name='date_completed',
        ),
    ]
