# Generated by Django 4.2.16 on 2024-12-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsp', '0012_alter_staffneopactivities_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNeopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption_date', models.DateField(blank=True, null=True)),
                ('date_end_third', models.DateField(blank=True, null=True)),
                ('date_end_sixth', models.DateField(blank=True, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neop_info_activities', to='rsp.newlyhiredstaff')),
            ],
        ),
    ]
